version: "3.9"

services:
  booking-service-db:
    container_name: booking-service-db
    image: "mcr.microsoft.com/mssql/server:latest"
    user: root
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Mydatabase!1"
      ACCEPT_EULA: "Y"
    volumes:
      - "./dockerData/data/:/var/opt/mssql/data/"
      - "./dockerData/log/:/var/opt/mssql/log/"
      - "./dockerData/secrets/:/var/opt/mssql/secrets/"      
    networks:
      - booking-app-net
  booking-service-app:
    container_name: booking-service-app
    build: .
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5000"
      APPSETTINGS_ROUTE_SERVICE_BASE_URL: "http://route-service:5005/api/"
    networks:
      - booking-app-net
    depends_on:
      - booking-service-db
networks:
  booking-app-net:
    external: true
# For this to work, you must manually create network: docker network create booking-app-net